### ISSUE TITLE
Deploy DOI Search to pds.nasa.gov

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds-react#21]
## 💡 Description

[The wiki](https://wiki.jpl.nasa.gov/display/PDSEN/DOI+Service+Installation+and+Deployment) gets us part of the way there, need to know what ports need to be opened/scanned to make the query accessible on pds.nasa.gov.

- [x] Work with SAs to deploy latest DOI service on pds.nasa.gov
- [x] Update with latest DOI from datacite
- [x] Update [Citing PDS Data page](https://pds.nasa.gov/datastandards/citing/) to link to pds.nasa.gov deployment

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I have a question from Aaron on the DOI service deployment. Do we want it to be deplpoyed on both pds-prod1 and pds-prod2 ?

I would say pds-prod1 is enough 1) since the database would not be synchornized with pds-prod2 (unless we setup a specifc synchronization mechanism or choose a shared location between both server). And 2) the deployment is somehow an interim solution before we migrate to AWS.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl agreed. Can we also make sure the database and tools appropriate directories are synced to AWS along with our existing tools and services?

**Comment by jordanpadams** [comment]
We are live! https://pds.nasa.gov/datastandards/citing/
